version: "3.8"

services:

  flask:
    build: ./flask

    container_name: flask

    env_file:
      - flask.env

    ports:
      - "8888:8888"

  nginx:
    build: ./nginx

    container_name: nginx

    ports:
      - "80:80"
      - "443:443"

    depends_on:
      - flask
